/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld

#include <jni.h>
#include <iostream>

/*
 * Class:     HelloWorld
 * Method:    sayHello
 * Signature: ()V
 */
extern "C" 
JNIEXPORT void JNICALL Java_HelloWorld_sayHello(JNIEnv*, jobject);

/*
 * Class:     HelloWorld
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
extern "C"
JNIEXPORT jstring JNICALL Java_HelloWorld_getString(JNIEnv*, jobject);


#endif // _Included_HelloWorld
