/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class HelloWorld */

#ifndef _Included_BROTLI_ENCODER_JNI
#define _Included_BROTLI_ENCODER_JNI

#include <jni.h>

#include <cstddef>
#include <cstdint>
#include <new>

#include <brotli/encode.h>
#include <brotli/shared_dictionary.h>

namespace {
/* A structure used to persist the encoder's state in between calls. */
typedef struct EncoderHandle {
    BrotliEncoderState* state;

    jobject dictionary_refs[15];
    size_t dictionary_count;

    uint8_t* input_start;
    size_t input_offset;
    size_t input_last;
} EncoderHandle;

/* Obtain handle from opaque pointer. */
EncoderHandle* getHandle(void* opaque) {
    return static_cast<EncoderHandle*>(opaque);
}

} /* namespace */

extern "C" {

JNIEXPORT jobject JNICALL Java_io_github_EncoderJNI_nativeCreate(
    JNIEnv* env, jobject /*jobj*/, jlongArray ctx);

JNIEXPORT void JNICALL Java_io_github_EncoderJNI_nativePush(
    JNIEnv* env, jobject /*jobj*/, jlongArray ctx, jint input_length);

JNIEXPORT jobject JNICALL Java_io_github_EncoderJNI_nativePull(
    JNIEnv* env, jobject /*jobj*/, jlongArray ctx);

JNIEXPORT void JNICALL Java_io_github_EncoderJNI_nativeDestroy(
    JNIEnv* env, jobject /*jobj*/, jlongArray ctx);

JNIEXPORT jboolean JNICALL
Java_io_github_EncoderJNI_nativeAttachDictionary(
    JNIEnv* env, jobject /*jobj*/, jlongArray ctx, jobject dictionary);

JNIEXPORT void JNICALL
Java_io_github_EncoderJNI_nativeDestroyDictionary(
    JNIEnv* env, jobject /*jobj*/, jobject dictionary);

JNIEXPORT jobject JNICALL
Java_io_github_EncoderJNI_nativePrepareDictionary(
    JNIEnv* env, jobject /*jobj*/, jobject dictionary, jlong type);
}

#endif  // _Included_BROTLI_ENCODER_JNI
